### np.sort

Return a sorted copy of an array.

In [8]:
# code

import numpy as np
a = np.random.randint(1,100,15)
a
# print(a)

array([15, 78, 84, 78, 16, 16, 25, 98, 51, 87,  3, 56, 44, 74,  5])

In [9]:
np.sort(a)

array([ 3,  5, 15, 16, 16, 25, 44, 51, 56, 74, 78, 78, 84, 87, 98])

In [10]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[27, 29,  9, 70],
       [26, 31, 93, 88],
       [44, 70, 26,  2],
       [97, 97,  9, 28],
       [22, 47, 37, 76],
       [51, 19, 93,  7]])

In [11]:
np.sort(b)

array([[ 9, 27, 29, 70],
       [26, 31, 88, 93],
       [ 2, 26, 44, 70],
       [ 9, 28, 97, 97],
       [22, 37, 47, 76],
       [ 7, 19, 51, 93]])

In [12]:
np.sort(a)[::-1]

array([98, 87, 84, 78, 78, 74, 56, 51, 44, 25, 16, 16, 15,  5,  3])

In [13]:
np.sort(b,axis=0)

array([[22, 19,  9,  2],
       [26, 29,  9,  7],
       [27, 31, 26, 28],
       [44, 47, 37, 70],
       [51, 70, 93, 76],
       [97, 97, 93, 88]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

In [14]:
np.append(a,200)

array([ 15,  78,  84,  78,  16,  16,  25,  98,  51,  87,   3,  56,  44,
        74,   5, 200])

In [15]:
b

array([[27, 29,  9, 70],
       [26, 31, 93, 88],
       [44, 70, 26,  2],
       [97, 97,  9, 28],
       [22, 47, 37, 76],
       [51, 19, 93,  7]])

In [16]:
# np.append(b,np.ones((b.shape[0],1)),axis=1)

np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[2.70000000e+01, 2.90000000e+01, 9.00000000e+00, 7.00000000e+01,
        8.25777243e-01],
       [2.60000000e+01, 3.10000000e+01, 9.30000000e+01, 8.80000000e+01,
        6.57218767e-01],
       [4.40000000e+01, 7.00000000e+01, 2.60000000e+01, 2.00000000e+00,
        6.64232367e-01],
       [9.70000000e+01, 9.70000000e+01, 9.00000000e+00, 2.80000000e+01,
        4.59009110e-01],
       [2.20000000e+01, 4.70000000e+01, 3.70000000e+01, 7.60000000e+01,
        4.85642344e-01],
       [5.10000000e+01, 1.90000000e+01, 9.30000000e+01, 7.00000000e+00,
        4.61088714e-02]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [17]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [18]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [19]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [20]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [21]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

In [22]:
# code
a.shape

(15,)

In [23]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [24]:
np.expand_dims(a,axis=1)

array([[15],
       [78],
       [84],
       [78],
       [16],
       [16],
       [25],
       [98],
       [51],
       [87],
       [ 3],
       [56],
       [44],
       [74],
       [ 5]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [25]:
a

array([15, 78, 84, 78, 16, 16, 25, 98, 51, 87,  3, 56, 44, 74,  5])

In [26]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  2,  3,  7,  8,  9, 11, 13], dtype=int64),)

In [27]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([15,  0,  0,  0, 16, 16, 25,  0,  0,  0,  3,  0, 44,  0,  5])

In [28]:
### replace in even numbers

np.where(a%2 == 0,0,a)

array([15,  0,  0,  0,  0,  0, 25,  0, 51, 87,  3,  0,  0,  0,  5])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [29]:
a

array([15, 78, 84, 78, 16, 16, 25, 98, 51, 87,  3, 56, 44, 74,  5])

In [30]:
np.argmax(a)

7

In [31]:
b

array([[27, 29,  9, 70],
       [26, 31, 93, 88],
       [44, 70, 26,  2],
       [97, 97,  9, 28],
       [22, 47, 37, 76],
       [51, 19, 93,  7]])

In [32]:
np.argmax(b,axis=0)

array([3, 3, 1, 1], dtype=int64)

In [33]:
np.argmax(b,axis=1)

array([3, 2, 1, 0, 3, 2], dtype=int64)

In [34]:
# np.argmin

np.argmin(a)

10

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis

In [35]:
a

array([15, 78, 84, 78, 16, 16, 25, 98, 51, 87,  3, 56, 44, 74,  5])

In [36]:
np.cumsum(a)

array([ 15,  93, 177, 255, 271, 287, 312, 410, 461, 548, 551, 607, 651,
       725, 730])

In [37]:
b

array([[27, 29,  9, 70],
       [26, 31, 93, 88],
       [44, 70, 26,  2],
       [97, 97,  9, 28],
       [22, 47, 37, 76],
       [51, 19, 93,  7]])

In [38]:
np.cumsum(b,axis=1)

array([[ 27,  56,  65, 135],
       [ 26,  57, 150, 238],
       [ 44, 114, 140, 142],
       [ 97, 194, 203, 231],
       [ 22,  69, 106, 182],
       [ 51,  70, 163, 170]])

In [39]:
np.cumsum(b)

array([  27,   56,   65,  135,  161,  192,  285,  373,  417,  487,  513,
        515,  612,  709,  718,  746,  768,  815,  852,  928,  979,  998,
       1091, 1098])

In [40]:
# np.cumprod
np.cumprod(a)

array([         15,        1170,       98280,     7665840,   122653440,
        1962455040,  1816735744,  1946443776,   484384768,  -808198144,
        1870372864,  1661665280,    98828288, -1276641280, -2088239104])

In [41]:
a

array([15, 78, 84, 78, 16, 16, 25, 98, 51, 87,  3, 56, 44, 74,  5])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [42]:
# code
a

array([15, 78, 84, 78, 16, 16, 25, 98, 51, 87,  3, 56, 44, 74,  5])

In [43]:
np.percentile(a,50)

51.0

In [44]:
np.median(a)

51.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [45]:
# code
a

array([15, 78, 84, 78, 16, 16, 25, 98, 51, 87,  3, 56, 44, 74,  5])

In [46]:
np.histogram(a,bins=[0,50,100])

(array([7, 8], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

In [47]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [48]:
# code
a


array([15, 78, 84, 78, 16, 16, 25, 98, 51, 87,  3, 56, 44, 74,  5])

In [49]:
items = [10,20,30,40,50,60,70,80,90,100]

# np.isin(a,items)

a[np.isin(a,items)]

array([], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [50]:
# code
a

array([15, 78, 84, 78, 16, 16, 25, 98, 51, 87,  3, 56, 44, 74,  5])

<!-- 55:14:00 -->

In [51]:
np.flip(a)

array([ 5, 74, 44, 56,  3, 87, 51, 98, 25, 16, 16, 78, 84, 78, 15])

In [52]:
b

array([[27, 29,  9, 70],
       [26, 31, 93, 88],
       [44, 70, 26,  2],
       [97, 97,  9, 28],
       [22, 47, 37, 76],
       [51, 19, 93,  7]])

In [55]:
np.flip(b,axis=1)

array([[70,  9, 29, 27],
       [88, 93, 31, 26],
       [ 2, 26, 70, 44],
       [28,  9, 97, 97],
       [76, 37, 47, 22],
       [ 7, 93, 19, 51]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [58]:
# code
a

array([110, 530,  84,  78,  16,  16,  25,  98,  51,  87,   3,  56,  44,
        74,   5])

In [57]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [59]:
# code
a

array([110, 530,  84,  78,  16,  16,  25,  98,  51,  87,   3,  56,  44,
        74,   5])

In [61]:
np.delete(a,[0,2,4])

# np.delete(a,0)

array([530,  78,  16,  25,  98,  51,  87,   3,  56,  44,  74,   5])

### Set functions
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [62]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [63]:
np.intersect1d(m,n)

array([3, 4, 5])

In [64]:
np.setdiff1d(n,m)

array([6, 7])

In [65]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [66]:
m[np.in1d(m,1)]

array([1])

### np.clip
numpy.clip() function is used to Clip (limit) the values in an array.

In [67]:
# code
a

array([110, 530,  84,  78,  16,  16,  25,  98,  51,  87,   3,  56,  44,
        74,   5])

In [68]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 75, 25, 25, 25, 75, 51, 75, 25, 56, 44, 74, 25])