### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

**Creating Numpy Arrays**

In [3]:
import numpy as np


a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
# 2D or 3D array

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:

c = np.array([[1,2],[3,4],[5,6],[7,8]])
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
# dtype

# np.array([1,2,3],dtype=float)
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [11]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [17]:
# with reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [4]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
# np.random
np.random.random((3,4))

array([[0.23426159, 0.35564575, 0.89949326, 0.08532395],
       [0.55836651, 0.67010894, 0.17589995, 0.46875393],
       [0.48901428, 0.38531268, 0.88572289, 0.13208887]])

In [22]:
# np.linspace
np.linspace(-10,10,10)#,dtype=int)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [23]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Array Attributes**

In [47]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [32]:
# ndim
a3.ndim

3

In [38]:
# shape
print(a3.shape)
a3

# a3.shape

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
# size
print(a2.size)
a2

# a3.size

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [48]:
# itemsize
a3.itemsize

4

In [46]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


**Changing Datatype**

In [54]:
# astype
# a3.astype(np.int32)
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

**Array Operations**

In [50]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [56]:
# relational                                                                                                                                                                                                                                                                                                                                                                                                
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [59]:
# vector operations
# arithmetic
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

**Array Functions**

In [60]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[29., 71., 78.],
       [93., 62.,  7.],
       [ 6., 59., 70.]])

**Array Functions**

In [17]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[33., 21., 24.],
       [38., 43., 71.],
       [69., 52., 60.]])

In [15]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([0.00461848, 0.42151977, 0.01038481])

In [20]:
# mean/median/std/var
np.var(a1,axis=1)
# np.std(a1,axis=1)

array([ 26.        , 210.88888889,  48.22222222])

In [18]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.99991186,  0.83665564, -0.90557836],
       [ 0.29636858, -0.83177474,  0.95105465],
       [-0.11478481,  0.98662759, -0.30481062]])

In [24]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [29]:
# log and exponents
np.exp(a1)

array([[2.14643580e+14, 1.31881573e+09, 2.64891221e+10],
       [3.18559318e+16, 4.72783947e+18, 6.83767123e+30],
       [9.25378173e+29, 3.83100800e+22, 1.14200739e+26]])

In [34]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)


array([[ 4., 18., 83.],
       [93., 99., 23.]])

**Indexing and Slicing**

In [35]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [41]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
a2[1,0]

4

In [48]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [54]:
a3[0,1,0]

2

In [58]:
a3[1,1,0]

6

In [59]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a1[2:5:2]

array([2, 4])

In [67]:
a2[0,:]

array([0, 1, 2, 3])

In [68]:
a2[:,2]

array([ 2,  6, 10])

In [69]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [73]:
# a2[::,2]
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [77]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
# 1:33:00