### np.sort

Return a sorted copy of an array.

In [18]:
# code

import numpy as np
a = np.random.randint(1,100,15)
a
# print(a)

array([ 1, 56, 31, 67, 99, 77, 86, 52, 80, 24, 43, 18, 76, 33, 74])

In [19]:
np.sort(a)

array([ 1, 18, 24, 31, 33, 43, 52, 56, 67, 74, 76, 77, 80, 86, 99])

In [20]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[76,  6, 81, 81],
       [65, 85, 82, 24],
       [53, 59, 69, 53],
       [31, 71, 13, 77],
       [24, 71, 57,  8],
       [46, 54, 63, 71]])

In [21]:
np.sort(b)

array([[ 6, 76, 81, 81],
       [24, 65, 82, 85],
       [53, 53, 59, 69],
       [13, 31, 71, 77],
       [ 8, 24, 57, 71],
       [46, 54, 63, 71]])

In [22]:
np.sort(a)[::-1]

array([99, 86, 80, 77, 76, 74, 67, 56, 52, 43, 33, 31, 24, 18,  1])

In [23]:
np.sort(b,axis=0)

array([[24,  6, 13,  8],
       [31, 54, 57, 24],
       [46, 59, 63, 53],
       [53, 71, 69, 71],
       [65, 71, 81, 77],
       [76, 85, 82, 81]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

In [24]:
np.append(a,200)

array([  1,  56,  31,  67,  99,  77,  86,  52,  80,  24,  43,  18,  76,
        33,  74, 200])

In [25]:
b

array([[76,  6, 81, 81],
       [65, 85, 82, 24],
       [53, 59, 69, 53],
       [31, 71, 13, 77],
       [24, 71, 57,  8],
       [46, 54, 63, 71]])

In [26]:
# np.append(b,np.ones((b.shape[0],1)),axis=1)

np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[76.        ,  6.        , 81.        , 81.        ,  0.82089994],
       [65.        , 85.        , 82.        , 24.        ,  0.63298948],
       [53.        , 59.        , 69.        , 53.        ,  0.3156997 ],
       [31.        , 71.        , 13.        , 77.        ,  0.10232375],
       [24.        , 71.        , 57.        ,  8.        ,  0.24655662],
       [46.        , 54.        , 63.        , 71.        ,  0.44049033]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [27]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [30]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [31]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [32]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [33]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

In [34]:
# code
a.shape

(15,)

In [37]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [38]:
np.expand_dims(a,axis=1)

array([[ 1],
       [56],
       [31],
       [67],
       [99],
       [77],
       [86],
       [52],
       [80],
       [24],
       [43],
       [18],
       [76],
       [33],
       [74]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [39]:
a

array([ 1, 56, 31, 67, 99, 77, 86, 52, 80, 24, 43, 18, 76, 33, 74])

In [40]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  3,  4,  5,  6,  7,  8, 12, 14], dtype=int64),)

In [41]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 1,  0, 31,  0,  0,  0,  0,  0,  0, 24, 43, 18,  0, 33,  0])

In [42]:
### replace in even numbers

np.where(a%2 == 0,0,a)

array([ 1,  0, 31, 67, 99, 77,  0,  0,  0,  0, 43,  0,  0, 33,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [43]:
a

array([ 1, 56, 31, 67, 99, 77, 86, 52, 80, 24, 43, 18, 76, 33, 74])

In [44]:
np.argmax(a)

4

In [45]:
b

array([[76,  6, 81, 81],
       [65, 85, 82, 24],
       [53, 59, 69, 53],
       [31, 71, 13, 77],
       [24, 71, 57,  8],
       [46, 54, 63, 71]])

In [46]:
np.argmax(b,axis=0)

array([0, 1, 1, 0], dtype=int64)

In [47]:
np.argmax(b,axis=1)

array([2, 1, 2, 3, 1, 3], dtype=int64)

In [48]:
# np.argmin

np.argmin(a)

0

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis

In [49]:
a

array([ 1, 56, 31, 67, 99, 77, 86, 52, 80, 24, 43, 18, 76, 33, 74])

In [53]:
np.cumsum(a)

array([  1,  57,  88, 155, 254, 331, 417, 469, 549, 573, 616, 634, 710,
       743, 817])

In [50]:
b

array([[76,  6, 81, 81],
       [65, 85, 82, 24],
       [53, 59, 69, 53],
       [31, 71, 13, 77],
       [24, 71, 57,  8],
       [46, 54, 63, 71]])

In [56]:
np.cumsum(b,axis=1)

array([[ 76,  82, 163, 244],
       [ 65, 150, 232, 256],
       [ 53, 112, 181, 234],
       [ 31, 102, 115, 192],
       [ 24,  95, 152, 160],
       [ 46, 100, 163, 234]])

In [57]:
np.cumsum(b)

array([  76,   82,  163,  244,  309,  394,  476,  500,  553,  612,  681,
        734,  765,  836,  849,  926,  950, 1021, 1078, 1086, 1132, 1186,
       1249, 1320])

In [58]:
# np.cumprod
np.cumprod(a)

array([          1,          56,        1736,      116312,    11514888,
         886646376, -1057822992,   827779264,  1797831680,   198287360,
         -63578112, -1144406016, -1075511296, -1132134400,  2121400320])

In [59]:
a

array([ 1, 56, 31, 67, 99, 77, 86, 52, 80, 24, 43, 18, 76, 33, 74])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [60]:
# code
a

array([ 1, 56, 31, 67, 99, 77, 86, 52, 80, 24, 43, 18, 76, 33, 74])

In [67]:
np.percentile(a,50)

56.0

In [63]:
np.median(a)

56.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [68]:
# code
a

array([ 1, 56, 31, 67, 99, 77, 86, 52, 80, 24, 43, 18, 76, 33, 74])

In [69]:
np.histogram(a,bins=[0,50,100])

(array([6, 9], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

In [70]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [71]:
# code
a


array([ 1, 56, 31, 67, 99, 77, 86, 52, 80, 24, 43, 18, 76, 33, 74])

In [76]:
items = [10,20,30,40,50,60,70,80,90,100]

# np.isin(a,items)

a[np.isin(a,items)]

array([80])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

<!-- 55:14:00 -->